[package]
name = "physics"
version = "0.1.0"
authors = []

[lib]
name = "physics"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.18.0"
rustler_codegen = "0.18.0"
lazy_static = "1.0"
nalgebra = "0.16.5"
ncollide2d = "0.17.1"
nphysics2d = "0.9.2"
